services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aamarpay_web
    command: gunicorn aamarpay_project.wsgi:application --bind 0.0.0.0:8000
    working_dir: /app/aamarpay_project
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aamarpay_celery
    command: celery -A aamarpay_project worker --loglevel=info
    working_dir: /app/aamarpay_project
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: aamarpay_redis
    ports:
      - "6379:6379"
